
--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue 
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating):: NUMERIC,2) as "Average product rating"
from customer
group by 1 
order by 2 desc
limit 5;

--Q4. Comparison of the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, ROUND(AVG(purchase_amount), 2) as "Average purchase amount"
from customer
where shipping_type in ('Standard', 'Express')
group by 1;


--Q5. Do subscribed customers spend more?

select subscription_status, 
COUNT(customer_id) as "Total customers",
ROUND(AVG(purchase_amount), 2 ) as avg_spend,
SUM(purchase_amount) as total_revenue
from customer 
GROUP BY subscription_status
order by 3,4 desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer 
group by 1
order by 2 desc
limit 5;


--Q7. Segmentation of customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and showing the count of each segment. 

with customer_type as(
select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal' 
END as customer_segment
from customer)

select customer_segment, 
COUNT(*) as "Count of segment"
from customer_type
group by 1
order by 2 desc;

--Q8. What are the top 3 most purchased products within each category? 

with numbers as(
select category, item_purchased, 
COUNT(*) as number_of_purchases,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
from customer 
group by 1,2)

select item_rank, category, item_purchased, number_of_purchases
from numbers
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, 
COUNT(customer_id) as "Repeat buyers"
from customer
where previous_purchases > 5
group by 1;

--Q10. What is the revenue contribution of each age group? 

select age_group, ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by 1
order by 2 desc;



